name: CD

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:
  # pull_request:
  # uncomment the above to test CD in a PR

jobs:
  call-external:
    uses: jina-ai/workflows-executors/.github/workflows/cd.yml@test-read-own-secret
    with:
      event_name: ${{ github.event_name }}