name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  push-executors:
    runs-on: ubuntu-latest
    container:
      image: jinaai/jina:master-standard
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag env var
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: push to Hubble
        run: |
          bash ./.github/workflows/scripts/push.sh .
        env:
          token: ${{ secrets.GH_TOKEN }}
          GIT_TAG: $RELEASE_VERSION
