name: CD

on:
  push:
    branches:
    - $default-branch
  workflow_dispatch:
  #pull_request:

jobs:
  push-executors:
    runs-on: ubuntu-latest
    container:
      image: jinaai/jina:master-standard
      options: "--entrypoint /bin/bash"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: push to Hubble
        run: |
          bash ./.github/workflows/scripts/push.sh .
        env:
          token: ${{ secrets.GH_TOKEN }}
